version: "3.9"

services:
  configmanagement:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ConfigDB;User=sa;Password=SIOgtBQKzXIVfq43;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SIOgtBQKzXIVfq43
    ports:
      - "1433:1433"
      - "32769:32769"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  appnet: